# Generated by Django 4.1.5 on 2023-01-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('B', 'Basic'), ('I', 'Intermediary'), ('A', 'Advenced'), ('S', 'Specialist')], default='B', max_length=1)),
                ('duration', models.CharField(default='10 hours', max_length=10)),
                ('category', models.CharField(choices=[('M', 'Medicine'), ('T', 'Tech'), ('E', 'Engineering'), ('S', 'Sale')], default='T', max_length=1)),
            ],
        ),
    ]
