# Generated by Django 4.1.5 on 2023-01-18 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('B', 'Basic'), ('I', 'Intermediary'), ('A', 'Advenced'), ('S', 'Specialist')], default='B', max_length=1)),
                ('duration', models.CharField(default='10 hours', max_length=10)),
                ('category', models.CharField(default='T', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Studant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=60)),
                ('rg', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=9)),
                ('cep', models.CharField(max_length=8)),
                ('date_birth', models.DateField()),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField()),
                ('deadline', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.course')),
                ('studant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.studant')),
            ],
        ),
    ]
